spring:
  data:
    mongodb:
      database: super
  mongodb:
    embedded:
      version: 3.5.5

#mongock:
#  #runner-type: "ApplicationRunner" # default
#  runner-type: "InitializingBean"
#  change-logs-scan-package:
#    - com.example.mongockdemo.mongock.changelog


logging:
  level:
    ROOT: ERROR