### Embedded mongo ###

#spring:
#  data:
#    mongodb:
#      database: testbookhw008
#  mongodb:
#    embedded:
#      version: 3.5.5

### Local mongoDB server ###

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testbookhw008
#TODO:переставить
### Mongock ###

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.glavs.hw008.mongock.changelog


logging:
  level:
    ROOT: error