spring:
  data:
    mongodb:
      database: super
  mongodb:
    embedded:
      version: 3.5.5

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.glavs.hw008.mongock.changelog


logging:
  level:
    ROOT: info