spring:
  datasource:
     url: jdbc:h2:mem:bookdb
  data:
    mongodb:
      database: bookhw008
  mongodb:
      embedded:
        version: 3.5.5
  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  batch:
    job:
      enabled: false
logging:
  level:
    ROOT: error