spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  #     url: jdbc:h2:mem:bookdb
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    ROOT: info