spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/bookdb #ПОМЕНЯТЬ НА MEM!!
    url: jdbc:h2:mem:bookdb
#    username: sa
#    password: 11
  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql
