spring:
  datasource:
     url: jdbc:h2:mem:bookdb
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false


logging:
  level:
    ROOT: info
server:
  error:
    path: "/err"