DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE BOOKS
(
    ID        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AUTHOR_ID INT         NOT NULL,
    GENRE_ID  INT         NOT NULL,
    TITLE     VARCHAR(50) NOT NULL
);
CREATE TABLE GENRES
(
    ID    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GENRE VARCHAR(30) NOT NULL
);
CREATE TABLE AUTHORS
(
    ID       INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME     VARCHAR(30) NOT NULL,
    SURNAME  VARCHAR(30) NOT NULL,
    INITIALS VARCHAR(6)  NOT NULL
);
CREATE TABLE COMMENTS
(
    ID       INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEXT     CLOB(10K) NOT NULL,
    DATE     DATE
);
