DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS COMMENTS;


CREATE TABLE BOOKS
(
    BOOK_ID        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AUTHOR_ID INT         NOT NULL,
    GENRE_ID  INT         NOT NULL,
    TITLE     VARCHAR(50) NOT NULL
);
CREATE TABLE GENRES
(
    GENRE_ID    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GENRE VARCHAR(30) NOT NULL
);
CREATE TABLE AUTHORS
(
    AUTHOR_ID       INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME     VARCHAR(30) NOT NULL,
    SURNAME  VARCHAR(30) NOT NULL,
    INITIALS VARCHAR(6)  NOT NULL
);
CREATE TABLE COMMENTS
(
    COMMENT_ID       INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMMENT_TEXT     CLOB(10K) NOT NULL,
    AUTHOR_NICK      VARCHAR(30) NOT NULL,
    COMMENT_DATE     DATE
);
