### Embedded mongo ###

spring:
  data:
    mongodb:
      database: bookhw011
  mongodb:
    embedded:
      version: 4.4.6


### Local mongoDB server ###

#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: testbookhw011



logging:
  level:
    ROOT: info