DROP TABLE IF EXISTS composers;

CREATE TABLE composers
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    family    VARCHAR(255),
    birthdate date,
    CONSTRAINT pk_composers PRIMARY KEY (id)
);

insert into composers(family, birthdate) values ('Bach', '1685-03-21');
insert into composers(family, birthdate) values ('Haydn', '1732-03-31');
insert into composers(family, birthdate) values ('Mozart', '1756-01-27');
insert into composers(family, birthdate) values ('Beethoven', '1770-12-17');
insert into composers(family, birthdate) values ('Rachmaninov', '1873-03-20');